#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh --blocks

xsetroot -cursor_name left_ptr &

bspc monitor eDP-1   -d A B C D E
bspc monitor HDMI-1  -d 1 2 3 4 5

if  xrandr -q | grep "HDMI-1" > /dev/null
then
        bspc config -m eDP-1 top_padding 0
else

        bspc config -m eDP-1 top_padding 36
fi

bspc config -m HDMI-1 top_padding 36

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true
