require('config.colorscheme')
require('config.nerdtree')
require('config.telescope')
--require('config.lualine')
require('config.lsp')
require('config.compe')
--require('config.neoformat')
require('config.barbar')
